services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: |
        echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb:27017'}]}) }" | mongosh --port 27017 --quiet
      start_period: 0s
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - oz-network

volumes:
  mongodb_data:

networks:
  oz-network:
    driver: bridge
